name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Choose your PHP version

    - name: Install dependencies
      run: composer install

    - name: Run SonarQube Scanner
      run: |
        sonar-scanner \
          -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
          -Dsonar.host.url=http://localhost:8080 \
          -Dsonar.login=$SONARQUBE_AUTH_TOKEN

    - name: Upload SonarQube results
      uses: actions/upload-artifact@v2
      with:
        name: sonarqube-report
        path: .scannerwork/report-task.txt

