name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Choose your PHP version

    - name: Install dependencies
      run: composer install

    - name: Install SonarQube Scanner
      run: |
        # Download and install SonarQube Scanner
        curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner.zip
        export PATH=$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin

    - name: Run SonarQube Scanner
      run: |
        sonar-scanner \
          -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONARQUBE_AUTH_TOKEN

    - name: Upload SonarQube results
      uses: actions/upload-artifact@v2
      with:
        name: sonarqube-report
        path: .scannerwork/report-task.txt
